- name: Criar 500 Namespaces no OpenShift com Deploy e Rota
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Criar Namespaces
      k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: "teste{{ '%03d' | format(item) }}"
      loop: "{{ range(1, 501) | list }}"

    - name: Criar Deployments
      k8s:
        state: present
        namespace: "teste{{ '%03d' | format(item) }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: tinyweb
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: tinyweb
            template:
              metadata:
                labels:
                  app: tinyweb
              spec:
                containers:
                  - name: tinyweb
                    image: docker.io/lasher/tinyweb-static
                    ports:
                      - containerPort: 8080
      loop: "{{ range(1, 501) | list }}"

    - name: Criar Serviços
      k8s:
        state: present
        namespace: "teste{{ '%03d' | format(item) }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: tinyweb
          spec:
            selector:
              app: tinyweb
            ports:
              - protocol: TCP
                port: 80
                targetPort: 8080
      loop: "{{ range(1, 501) | list }}"

    - name: Criar Rotas
      k8s:
        state: present
        namespace: "teste{{ '%03d' | format(item) }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: tinyweb
          spec:
            to:
              kind: Service
              name: tinyweb
            port:
              targetPort: 80
      loop: "{{ range(1, 501) | list }}"
